//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mushroom_classification
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mushroom
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string edible { get; set; }
        public string bruises { get; set; }
        public string gill_spacing { get; set; }
        public string gill_size { get; set; }
        public string stalk_surface_above_ring { get; set; }
        public string stalk_surface_below_ring { get; set; }
        public string ring_type { get; set; }
        public string population { get; set; }
        public string habitat { get; set; }
        public virtual User1 User1 { get; set; }

        public Mushroom()
        {

        }
        public Mushroom(Main.Mushroom input, string result)
        {
            bruises = input.bruises;
            gill_spacing = input.gill_spacing;
            gill_size = input.gill_size;
            stalk_surface_above_ring = input.stalk_surface_above_ring;
            stalk_surface_below_ring = input.stalk_surface_below_ring;
            ring_type = input.ring_type;
            population = input.population;
            habitat = input.habitat;
            UserID = input.UserID;
            edible = result;
        }
    }
}
